# Generated by Django 3.1.5 on 2021-01-19 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_auto_20210119_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 0, 36, 40, 889424)),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.ImageField(blank=True, default='2.jpg', upload_to=''),
        ),
    ]
